### Routes
GET http://localhost:3000/api/fligthPaths?origin=BCN&destiny=CMN

### Airports codes
GET http://localhost:3000/api/airports

### Airline codes
GET http://localhost:3000/api/airlines

### Cities codes
GET http://localhost:3000/api/cities

### Countries codes
GET http://localhost:3000/api/countries
################################
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "userId": "",
    "username":"user2",
    "password":"user2",
    "rol":"admin",
    "routes":[{}]

},
{
    "userId": "",
    "username":"user3",
    "password":"user3",
    "rol":"admin",
    "routes":[{}]

},
{
    "userId": "",
    "username":"user4",
    "password":"user4",
    "rol":"admin",
    "routes":[{}]

}

################################
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "userId": "",
    "username":"user4",
    "password":"user4",
    "rol":"admin",
    "routes":[{}]

}

################################
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "username":"user2",
    "password":"user2"
}
########
POST http://localhost:3000/api/user/flightpaths
Content-Type: application/json

{
    "airline_iata": "3O",
    "airline_icao": null,
    "departure_airport_iata": "BCN",
    "departure_airport_icao": null,
    "arrival_airport_iata": "CMN",
    "arrival_airport_icao": null,
    "codeshare": false,
    "transfers": 0,
    "planes": [
    "320"
    ]
}
### Routes
GET http://localhost:3000/api/user/flightpaths
### Routes
DELETE http://localhost:3000/api/user/flightpaths
Content-Type: application/json

{
    "airline_iata": "3O",
    "airline_icao": null,
    "departure_airport_iata": "BCN",
    "departure_airport_icao": null,
    "arrival_airport_iata": "CMN",
    "arrival_airport_icao": null,
    "codeshare": false,
    "transfers": 0,
    "planes": [
    "320"
    ]
}

### Routes
GET http://localhost:3000/api/user/delete/user2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0IiwiaWF0IjoxNjM0MTE3NDM3LCJleHAiOjE2MzQxMTc3Mzd9.dZ-9YrYp2zrLs-hDSNTjy_xOKZ1Zfm6u-u3hAooyfmc