################ Search
### Airlines codes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/airlines

### Airports codes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/airports

### Cities codes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/cities

### Countries codes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/countries

### Routes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/routes?origin=BCN&destiny=CMN

################ User
### Register
POST https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/register
Content-Type: application/json

{
    "username":"user1",
    "password":"user1"
}

### Login
POST https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/login
Content-Type: application/json

{
    "username":"user1",
    "password":"user1"
}

### Saved user routes
GET https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/routes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjM0MTIzMjk3LCJleHAiOjE2MzQxMjM1OTd9.M_Fyodbg6voTto3c-kd0X-g8Vkxo834eN-R0aCgojkQ

### Add user route (1)
POST https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjM0MTIzMjk3LCJleHAiOjE2MzQxMjM1OTd9.M_Fyodbg6voTto3c-kd0X-g8Vkxo834eN-R0aCgojkQ

{
    "airline_iata": "3O",
    "airline_icao": null,
    "departure_airport_iata": "BCN",
    "departure_airport_icao": null,
    "arrival_airport_iata": "MAD",
    "arrival_airport_icao": null,
    "codeshare": false,
    "transfers": 0,
    "planes": [
        "320"
    ]
}

### Add user routes ( array )
POST https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjM0MTIzMjk3LCJleHAiOjE2MzQxMjM1OTd9.M_Fyodbg6voTto3c-kd0X-g8Vkxo834eN-R0aCgojkQ

[
  {
    "airline_iata": "3O",
    "airline_icao": null,
    "departure_airport_iata": "BCN",
    "departure_airport_icao": null,
    "arrival_airport_iata": "CMN",
    "arrival_airport_icao": null,
    "codeshare": false,
    "transfers": 0,
    "planes": [
        "320"
    ]
},
{
    "airline_iata": "3O",
    "airline_icao": null,
    "departure_airport_iata": "MAD",
    "departure_airport_icao": null,
    "arrival_airport_iata": "TFS",
    "arrival_airport_icao": null,
    "codeshare": false,
    "transfers": 0,
    "planes": [
        "320"
    ]
  }
]

### Delete user routes
DELETE https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjM0MTIzMjk3LCJleHAiOjE2MzQxMjM1OTd9.M_Fyodbg6voTto3c-kd0X-g8Vkxo834eN-R0aCgojkQ

################ ADMIN
### Login as admin
POST https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}

### ADMIN DELETE users
DELETE https://proyecto-m1-enric-y-dan.herokuapp.com/api/user/user1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjM0MTIzNzczLCJleHAiOjE2MzQxMjQwNzN9.QkLoudID9bId_Pocywbf9lYPKiMibTko92ZGH5N74Vg